### ISSUE TITLE
Support GKE

### ISSUE THREAD

**Issue by xfumihiro** [gajus/lightship#14]
Thanks for the great lib!
However due to the different port requirement, lightship isn't usable for GKE.

[https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks)
> Note that the Service exposed through an Ingress must point to the same container port on which the readiness probe is enabled.

Would you consider to make this a middleware so it can use the same port?

**Comment by gajus** [comment]
That is talking about load-balancer, which is unrelated to Kubernetes Controller Manager. Lightship is specifically designed for working within Kubernetes cluster, not interactive with external services.
