### ISSUE TITLE
Would it be better to wait for the server close event instead of a fixed time?

### ISSUE THREAD

**Issue by zhaoyao91** [gajus/lightship#15]
In the README, I noticed it suggest wait some time before calling `server.close()`. According to the [node.js doc](https://nodejs.org/api/net.html#net_server_close_callback), could the following code snippet be better? Or is there some other consideration?

```js
lightship.registerShutdownHandler(() => {
  return new Promise((resolve, reject) => {
    server.close(err => {
      if (err) reject(err);
      else resolve();
    });
  });
});

```

**Comment by gajus** [comment]
Don't do that – you will kill active requests.

See:

* https://github.com/gajus/lightship#add-a-delay-before-stop-handling-incoming-requests
* https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/

**Comment by gajus** [comment]
Sorry, you won't kill active requests in this case. However, it is possible that the server might still receive requests after receiving the SIGKILL, i.e. you need to allow time to ensure that no more traffic is being routed to your pod instance.

**Comment by zhaoyao91** [comment]
Seems that the denay is a magic number since we don't know how many time it will take to switch iptables.

**Comment by gajus** [comment]
That is correct.
