### ISSUE TITLE
Question: Why are process signals not set when in "local mode"

### ISSUE THREAD

**Issue by jorgemsrs** [gajus/lightship#24]
Hi.

I'm curious about the rationale behind the decision of only listen to signals when "in Kubernetes". 
Can you shed some light about it?

https://github.com/gajus/lightship/blob/2f0d23b620abf56b2ac272d8a100b7697d7f8cc5/src/factories/createLightship.js#L232-L234

Thanks for your work.

**Comment by gajus** [comment]
When in development environment, you want your process to restart quickly after making any changes.
