### ISSUE TITLE
Readme contains dead link

### ISSUE THREAD

**Issue by fabianschwarzfritz** [gajus/lightship#26]
The README file of this repository contains a dead link under  the section "Best Practices" to this address: https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/ .  The address  returns a 404 not found. 

However, the article links is wrong on the website manning.com as well. Maybe there's an alternative source or explanation that could be linked?

**Comment by gajus** [comment]
https://web.archive.org/web/20200807161820/https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/
