### ISSUE TITLE
Should business server handle gracefully shutdown?

### ISSUE THREAD

**Issue by finian** [gajus/lightship#27]
The gracefully shutdown is applied to the new created express app (server):
https://github.com/gajus/lightship/blob/5cd9373098e3cb74c7049c14667d8de99494e004/src/factories/createLightship.js#L74-L80

What about the business one? Should we handle it manually (with `createHttpTerminator`)?

**Comment by gajus** [comment]
> Should we handle it manually (with createHttpTerminator)?

Yes
