### ISSUE TITLE
Prefix or custom urls for endpoints

### ISSUE THREAD

**Issue by giedrius-timinskis** [gajus/lightship#28]
Hello

I have a requirement to put all healthcheck endpoints behind a `/internal` prefix. 

What are your opinions on allowing users to either customise the endpoints, or supply a prefix?

I am happy to create a PR with proposed changes, but I thought you might have had specific reasons for not allowing custom endpoints. If you do, I'd be curious to hear them.

Thanks!

**Comment by gajus** [comment]
> I am happy to create a PR with proposed changes, but I thought you might have had specific reasons for not allowing custom endpoints. If you do, I'd be curious to hear them.

Health checks are under a custom, dedicated port, that should never be exposed to public. Therefore, there is no need for a special prefix.
