### ISSUE TITLE
Expose state logging

### ISSUE THREAD

**Issue by alexandervantrijffel** [gajus/lightship#37]
First of all, thanks for sharing this excellent package for application lifecycle management and serving endpoints for Kubernetes health probes.

We at Grandvision are investigating whether we can adopt Lightship. What is holding us back is that there is no possibility to inject our logging infrastructure based on Winston. And the information being logged by lightship is very useful for debugging and analysis. Can you consider to either support other loggers or introduce callbacks or events to inform consumers of the package about state changes?

**Comment by gajus** [comment]
If you really wanted to, you could always just override `ROARR.write` method.

```js
import {
  ROARR,
} from 'roarr';

ROARR.write = () => {};
```

No plans of supporting other loggers. Motivation explained [here](https://github.com/gajus/roarr#motivation).
