### ISSUE TITLE
Can I pass parameters to shutdown()?

### ISSUE THREAD

**Issue by vprasanth** [gajus/lightship#4]
I assumed I could, but looks like I can't. I send a PR if you like.

**Comment by gajus** [comment]
Can you illustrate what do you mean?

Shutdown is a custom function that you provide yourself.

**Comment by vprasanth** [comment]
Sure

```javascript
lightship.registerShutdownHandler((msg) => {
  console.log(msg);
  // do some task
});

// some error scenario
if (err) {
  lightship.shutdown(err);
}
```

Perhaps I misunderstood what `registerShutdownHandler` does. Perhaps it's just a way to setup multiple functions to be executed when `shutdown()` is called. I was thinking I could also pass parameters to those functions

**Comment by gajus** [comment]
> it's just a way to setup multiple functions to be executed when shutdown() is called

That^
