### ISSUE TITLE
module 'lightship' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by j-dogcoder** [gajus/lightship#45]
When importing lightship using ```import createLightship from "lightship";``` I get the console error 

`
SyntaxError: Named export 'createLightship' not found. The requested module 'lightship' is a CommonJS module, which may not support all module.exports as named exports.
`

**Comment by j-dogcoder** [comment]
Hey @gajus, was wondering if you saw this...

**Comment by j-dogcoder** [comment]
This is an issue for anyone who uses the import syntax, cause it prohibits them from using it.

**Comment by gajus** [comment]
Added a comment in PR.
