### ISSUE TITLE
Option to pass `Roarr` instance to lightship?

### ISSUE THREAD

**Issue by alphaone** [gajus/lightship#48]
Hey,

I am using `Roarr` in my application and enhance it with a couple of simple middlewares. It would be super-helpful, if I could pass this Roarr instance to lightship.

Do you think that is is doable?

Btw: Amazing work! Lightship is great software, that makes running my applications in Kubernetes a bliss 👌

**Comment by gajus** [comment]
Roarr is designed to not be passed around, i.e. It is assumed that applications/frameworks have their own separate instances of Roarr.

However, you can always achieve this using `Roarr.adopt()`.
