### ISSUE TITLE
Run shutdown handlers is paralle

### ISSUE THREAD

**Issue by gajus** [gajus/lightship#6]
Currently the shutdown handlers are executed sequentially.

Running shutdown handlers in parallel would potentially shorten the shutdown time.

Refer to https://github.com/gajus/lightship/issues/5#issuecomment-451775408 discussion.

**Comment by memelet** [comment]
I agree with @dcherman, that dependencies should be handled by registered handler.

**Comment by gajus** [comment]
This introduces unnecessary ambiguity. There is nothing stopping user from simply implementing their own collection of methods that need to be run in parallel, i.e.

```js
registerShutdownHandler(async () => {
  await Promise.all([
    userCollectionOfShutdownHandlers,
  ]);
});

```
